---
kind: pipeline
type: docker
name: default

steps:
- name: create unity package
  image: ghcr.io/monkiato/unity-packager:1.0.1
  commands:
  - unity-packager create -p JRPGBattleSystem -o jrpg-battle-system -i ".csproj" --add-assets-folder

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: publish_api_key
    files: jrpg-battle-system.unitypackage

trigger:
  ref:
    - refs/tags/*